### PR TITLE
fix: resolve GL lockups with VBOs, closes #51

### LINKED ISSUE #51: Lockups during world switching when Render Regions disabled
This has been an issue I've been experiencing for awhile and it's taken me some time to narrow it down enough to make some sort of tangible report on it.

As a point of reference, I'm using Fedora 35 and run Minecraft using Java 8u312 available in its repos. I have done most of my testing related to this bug while only using Patcher and OptiFine as enabled mods, using the latest possible version of Forge for 1.8.9 and 1.12.2. I've previously tested for this bug using other distributions of Java (Azul Zulu JDK 8, BellSoft Liberica JDK 8) and did not have a different experience. I use a locally built copy of Patcher typically, but I've experienced this bug using the release distributed on sk1er.club.

Without OptiFine's Render Regions option enabled, it is virtually guaranteed that I experience ~10 second lockups when switching between servers after doing so at least once beforehand. This happens when switching between servers on larger network servers such as Hypixel, as well as between separate servers from the server list. I initially tied this to the font rendering optimisations, but I experience the issue with them disabled. I also thought that the optimised cloud rendering may be playing a part but that also does not seem to be the case as it also happens with that setting, or both that setting and the aforementioned font rendering opitmisations, disabled.

I typically try to leave Render Regions disabled as I tend to experience worse performance in a lot of situations using them. Nothing within my game logs points to anything about this unfortunately, but I can upload a log for each 1.8.9 and 1.12.2 if desired, I may be missing something.

This is not an issue I've encountered on 1.8.9 with OptiFine and Forge only. Disabling Patcher's fast world swapping error only results in it happening consistently even from game start, albeit with more even and consistently lower lockup times. I'd hoped to provide more info on this but I'm not quite knowledge enough on what's actually happening with Render Regions enabled and with what Patcher does that would be relevant to this issue, to narrow it down further.

### PR DESCRIPTION
**Pull request by calcastor**
As described in [MC-162522](https://bugs.mojang.com/browse/MC-162522), the bug described in #51 is a result of binding to already removed VertexBuffers, which equal to -1 internally. This happens in the method bufferData within VertexBuffer, so cancel bufferData when glBufferId is equal to -1. This matches behaviour in later versions.

For some further context on #51, I had not always experienced this bug, but I can currently replicate it without fail on OptiFine with Forge, with and without Patcher. I suspect upstream changes and fixes in Mesa for AMDGPU resulted in the correct behaviour in turn making this bug more obvious.

Still not sure why I can never replicate it with OptiFine by itself or on Vanilla, but given that this is how newer versions handle this I think this is an appropriate fix.

I've been dogfooding this on 1.8.9 for the past couple days with no issue, but I have not tested as extensively on 1.12.2. Seems to fix it on both though.

### CODE REVIEW

File: src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import org.spongepowered.asm.mixin.injection.Inject;
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
+
+import java.nio.ByteBuffer;
+
+@Mixin(VertexBuffer.class)
+public abstract class VertexBuffer_ResolveLockups {
+    @Shadow private int glBufferId;
+
+    @Inject(method = "bufferData", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/renderer/vertex/VertexBuffer;bindBuffer()V"), cancellable = true)
```
Comment (DJtheRedstoner) [inline src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java:16]: This can be `@At("HEAD")`

**Review by DJtheRedstoner — CHANGES_REQUESTED** [review]
While these changes look reasonable, the fact that `bufferData` is being called after `deleteGlBuffers` indicates that this isn't addressing the root of the problem. Given the nature of this issue, my recommended way to further diagnose the issue would be to stick a breakpoint in `bufferData` with a condition of `glBufferId == -1`, and analyze the stacktrace and game state when the breakpoint is hit.

File: src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java (hunk 1 above)
Comment (calcastor) [reply src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java:16]: This was original `@At("HEAD")` but if it's there it will break OptiFine's Render Regions; OptiFine makes modifications here and does something else if Render Regions are enabled.

Comment (DJtheRedstoner) [reply src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java:16]: Please add a comment indicating that is the case.

File: src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.Shadow;
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.Inject;
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
+
+import java.nio.ByteBuffer;
+
+@Mixin(VertexBuffer.class)
+public abstract class VertexBuffer_ResolveLockups {
```
Comment (DJtheRedstoner) [inline src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java:13]: The mixin name should contain Mixin (`VertexBufferMixin_ResolveLockups`)

**Review by DJtheRedstoner — COMMENTED** [review]
After taking the time to analyze the code and test out alternative fixes, this seems like the best way to fix this issue. One final nitpick, then this has my approval.

File: src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java (hunk 2 above)
Comment (calcastor) [reply src/main/java/club/sk1er/patcher/mixins/bugfixes/VertexBuffer_ResolveLockups.java]: Done

**Review by DJtheRedstoner — APPROVED** [review]

**Review by Sychic — APPROVED** [review]
